### ISSUE TITLE
call missing in plugin/tpl.vim?

### ISSUE THREAD

**Issue by jesaerys** [EricGebhart/SAS-Vim#2]
After installing this plugin, I get the following error message every time I open vim:

```
Error detected while processing BufRead Auto commands for "*":
E492: Not an editor command: SetTagsetFileType()
```

In plugin/tpl.vim, I changed `autocmd BufReadPost * SetTagsetFileType()` to `autocmd BufReadPost * call SetTagsetFileType()` and I no longer get the error. The omission of `call` is a typo, yes?

I'm running Vim 7.4.488.

**Comment by EricGebhart** [comment]
It should not need the call. It is supposed to run the command directly. This has been working fine for me.  The function is defined directly above the autocmd. I will investigate.

**Comment by jesaerys** [comment]
OK. I'll just keep the `call` patched in for now because it suppresses the error message.

**Comment by jesaerys** [comment]
I forgot to mention that sas-vim seems to work as expected despite the error message. I have not thoroughly tested all of the sas-vim features, however (I currently only use it for syntax highlighting).

**Comment by EricGebhart** [comment]
The error is only related to automatic detection of tagset / proc template files.  If you load a tagset file and it does not come up in tpl-mode that would be the problem.  The Autocmd basically says to look at every file that is loaded and check it to see if it is a tagset template file.  That way the tpl-mode will come up automatically for those files.

**Comment by EricGebhart** [comment]
I have this working now. There were a couple of problems.
- The function was not registered as a command
- For files shorter than 30 lines the sniffer would never exit.
